default[:xcache][:mem_size] = "128M"
default[:xcache][:cpu_count] = "2"
default[:xcache][:slots] = "16K"
default[:xcache][:var_size] = "64M"
default[:xcache][:var_count] = "2"
default[:xcache][:var_slots] = "16K"